### ISSUE TITLE
peewee.DataError: invalid input for query argument $4: datetime.datetime(2022, 7, 6, 0, 0) (expected str, got datetime)

### ISSUE THREAD

**Issue by Apuyuseng** [klen/peewee-aio#5]
__version__ = "0.14.2"

database: postgres

Operation Examples:
```
await User.select().where(User.create_datetime<datetime.now()).count()
```

log:
```
Traceback (most recent call last):
....
  File "/opt/anaconda3/lib/python3.8/site-packages/peewee_aio/model.py", line 237, in count
    return await self.manager.count(self)
  File "/opt/anaconda3/lib/python3.8/site-packages/peewee_aio/manager.py", line 181, in count
    return await self.fetchval(query)
  File "/opt/anaconda3/lib/python3.8/site-packages/peewee_aio/manager.py", line 96, in fetchval
    return await self.aio_database.fetchval(sql, *params, **opts)
  File "/opt/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/opt/anaconda3/lib/python3.8/site-packages/peewee_aio/manager.py", line 393, in process
    yield query, params, constructor
  File "/opt/anaconda3/lib/python3.8/site-packages/peewee.py", line 2950, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/opt/anaconda3/lib/python3.8/site-packages/peewee.py", line 191, in reraise
    raise value.with_traceback(tb)
  File "/opt/anaconda3/lib/python3.8/site-packages/peewee_aio/manager.py", line 393, in process
    yield query, params, constructor
  File "/opt/anaconda3/lib/python3.8/site-packages/peewee_aio/manager.py", line 96, in fetchval
    return await self.aio_database.fetchval(sql, *params, **opts)
  File "/opt/anaconda3/lib/python3.8/site-packages/aio_databases/database.py", line 103, in fetchval
    return await conn.fetchval(query, *params, column=column, **options)
  File "/opt/anaconda3/lib/python3.8/site-packages/aio_databases/backends/__init__.py", line 155, in fetchval
    return await self._fetchval(sql, *params, column=column, **options)
  File "/opt/anaconda3/lib/python3.8/site-packages/aio_databases/backends/_asyncpg.py", line 62, in _fetchval
    return await conn.fetchval(query, *params, column=column, **options)
  File "/opt/anaconda3/lib/python3.8/site-packages/asyncpg/connection.py", line 645, in fetchval
    data = await self._execute(query, args, 1, timeout)
  File "/opt/anaconda3/lib/python3.8/site-packages/asyncpg/connection.py", line 1659, in _execute
    result, _ = await self.__execute(
  File "/opt/anaconda3/lib/python3.8/site-packages/asyncpg/connection.py", line 1684, in __execute
    return await self._do_execute(
  File "/opt/anaconda3/lib/python3.8/site-packages/asyncpg/connection.py", line 1731, in _do_execute
    result = await executor(stmt, None)
  File "asyncpg/protocol/protocol.pyx", line 183, in bind_execute
  File "asyncpg/protocol/prepared_stmt.pyx", line 197, in asyncpg.protocol.protocol.PreparedStatementState._encode_bind_msg
peewee.DataError: invalid input for query argument $4: datetime.datetime(2022, 7, 6, 0, 0) (expected str, got datetime)
```

**Comment by Apuyuseng** [comment]
create_datetime
